version: "3.9"

services:
    website:
        build:
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./netmanga_website:/netmanga_website
            - static_data:/vol/web
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        env_file: 
            - ./.env
            - ./.env.secret
        depends_on: 
            - db_migrate
    
    db_migrate:
        image: netmanga_website
        command: python manage.py migrate
        volumes:
            - ./netmanga_website:/netmanga_website
            - static_data:/vol/web
        env_file: 
            - ./.env
            - ./.env.secret
        depends_on: 
            - postgres
        
    postgres:
        hostname: postgres
        image: postgres
        ports:
            - "5432:5432"
        env_file: 
            - ./.env
            - ./.env.secret
        volumes: 
            - db-data:/var/lib/postgresql/data

volumes: 
    db-data:
    static_data: 