# Generated by Django 3.1.14 on 2022-07-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('Failed', 'Failed'), ('Reviewing', 'Reviewing'), ('Resolved', 'Resolved')], max_length=10)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
