# Generated by Django 3.1 on 2021-05-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_withdraworder'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraworder',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
