# Generated by Django 3.1 on 2021-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210409_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='coins_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='award',
            name='fiat_reward',
            field=models.FloatField(default=0.0),
        ),
    ]
