# Generated by Django 3.1.13 on 2021-12-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211201_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraworder',
            name='paypal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
