# Generated by Django 3.1.13 on 2021-12-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211206_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraworder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdraworder',
            name='paypal',
            field=models.CharField(max_length=10000),
        ),
    ]
