# Generated by Django 3.1 on 2021-04-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_coinpurchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
