# Generated by Django 3.1.13 on 2021-12-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211206_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinpurchaseorder',
            name='time',
        ),
        migrations.RemoveField(
            model_name='withdraworder',
            name='time',
        ),
        migrations.AddField(
            model_name='coinpurchaseorder',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='withdraworder',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
