# Generated by Django 3.1 on 2021-04-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_creator_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='earned_money',
            field=models.FloatField(default=0.0),
        ),
    ]
