# Generated by Django 3.1 on 2021-04-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_creator_earned_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='money',
        ),
    ]
