# Generated by Django 3.1 on 2021-04-19 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_creator_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapteraward',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
