# Generated by Django 3.1.13 on 2021-12-14 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import netmanga_website.apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211213_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('cover_picture', models.ImageField(blank=True, upload_to='coverpictures/')),
                ('plot', models.CharField(max_length=1000)),
                ('primary_Genre', models.CharField(blank=True, choices=[('Select', 'Select'), ('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Slice of Life', 'Slice of Life'), ('Romance', 'Romance'), ('Superhero', 'Superhero'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Supernatural', 'Supernatural'), ('Mystery', 'Mystery'), ('Sports', 'Sports'), ('Historical', 'Historical'), ('Heartwarming', 'Heartwarming'), ('Horror', 'Horror'), ('Informative', 'Informative')], max_length=18, null=True)),
                ('secondary_Genre', models.CharField(blank=True, choices=[('Select', 'Select'), ('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Slice of Life', 'Slice of Life'), ('Romance', 'Romance'), ('Superhero', 'Superhero'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Supernatural', 'Supernatural'), ('Mystery', 'Mystery'), ('Sports', 'Sports'), ('Historical', 'Historical'), ('Heartwarming', 'Heartwarming'), ('Horror', 'Horror'), ('Informative', 'Informative')], max_length=18, null=True)),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.creator')),
            ],
        ),
        migrations.CreateModel(
            name='OneShotImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=1000, upload_to=netmanga_website.apps.accounts.models.get_oneshot_image_filename)),
                ('no', models.IntegerField(null=True)),
                ('oneshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.oneshot')),
            ],
        ),
    ]
