# Generated by Django 3.1 on 2021-04-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210419_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='analytics',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='third_party_advertise',
        ),
    ]
