# Generated by Django 3.1.13 on 2021-12-19 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_oneshot_oneshotimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneShotComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('oneshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.oneshot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='ChapterComment',
        ),
        migrations.RenameModel(
            old_name='CommentRating',
            new_name='ChapterCommentRating',
        ),
        migrations.RenameModel(
            old_name='Rating',
            new_name='ChapterRating',
        ),
        migrations.CreateModel(
            name='ReportOneShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=1000)),
                ('oneshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.oneshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OneShotRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BooleanField(null=True)),
                ('oneshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.oneshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OneShotCommentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BooleanField(null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.oneshotcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OneShotAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.award')),
                ('oneshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.oneshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
