# Generated by Django 3.1.14 on 2021-12-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211219_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraworder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Succeeded', 'Succeeded')], max_length=10),
        ),
    ]
